# output for command: /apps/gent/RHEL8/cascadelake-ib/software/Python/3.10.4-GCCcore-11.3.0/bin/python -m pip install --prefix=/scratch/gent/vo/001/gvo00117/easybuild/RHEL8/cascadelake-ampere-ib/software/scenicplus/1.0.0-foss-2022a  --no-deps  --ignore-installed  --no-index  --no-build-isolation  .

Processing /tmp/vsc43810/easybuild/build/scenicplus/1.0.0/foss-2022a/pycistarget/pycistarget-1.0.2
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'
  error: subprocess-exited-with-error
  
   python setup.py egg_info did not run successfully.
   exit code: 1
  > [28 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/vsc43810/easybuild/build/scenicplus/1.0.0/foss-2022a/pycistarget/pycistarget-1.0.2/setup.py", line 8, in <module>
          setup(
        File "/apps/gent/RHEL8/cascadelake-ib/software/polars/0.15.6-foss-2022a/lib/python3.10/site-packages/setuptools/__init__.py", line 87, in setup
          return distutils.core.setup(**attrs)
        File "/apps/gent/RHEL8/cascadelake-ib/software/polars/0.15.6-foss-2022a/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 147, in setup
          _setup_distribution = dist = klass(attrs)
        File "/apps/gent/RHEL8/cascadelake-ib/software/polars/0.15.6-foss-2022a/lib/python3.10/site-packages/setuptools/dist.py", line 475, in __init__
          _Distribution.__init__(
        File "/apps/gent/RHEL8/cascadelake-ib/software/polars/0.15.6-foss-2022a/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 283, in __init__
          self.finalize_options()
        File "/apps/gent/RHEL8/cascadelake-ib/software/polars/0.15.6-foss-2022a/lib/python3.10/site-packages/setuptools/dist.py", line 899, in finalize_options
          ep(self)
        File "/apps/gent/RHEL8/cascadelake-ib/software/polars/0.15.6-foss-2022a/lib/python3.10/site-packages/setuptools/dist.py", line 919, in _finalize_setup_keywords
          ep.load()(self, ep.name, value)
        File "/apps/gent/RHEL8/cascadelake-ib/software/Python/3.10.4-GCCcore-11.3.0/lib/python3.10/site-packages/setuptools_scm/integration.py", line 75, in version_keyword
          _assign_version(dist, config)
        File "/apps/gent/RHEL8/cascadelake-ib/software/Python/3.10.4-GCCcore-11.3.0/lib/python3.10/site-packages/setuptools_scm/integration.py", line 51, in _assign_version
          _version_missing(config)
        File "/apps/gent/RHEL8/cascadelake-ib/software/Python/3.10.4-GCCcore-11.3.0/lib/python3.10/site-packages/setuptools_scm/__init__.py", line 106, in _version_missing
          raise LookupError(
      LookupError: setuptools-scm was unable to detect version for /tmp/vsc43810/easybuild/build/scenicplus/1.0.0/foss-2022a/pycistarget/pycistarget-1.0.2.
      
      Make sure you're either building from a fully intact git repository or PyPI tarballs. Most other sources (such as GitHub's tarballs, a git checkout without the .git folder) don't contain the necessary metadata and will not work.
      
      For example, if you're using pip, instead of https://github.com/user/proj/archive/master.zip use git+https://github.com/user/proj.git#egg=proj
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

 Encountered error while generating package metadata.
> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
