easyblock = 'PythonBundle'

name = 'awscli'
version = '2.17.52'

homepage = 'https://pypi.python.org/pypi/awscli'
description = 'Universal Command Line Environment for AWS'

toolchain = {'name': 'GCCcore', 'version': '13.2.0'}

builddependencies = [
    ('binutils', '2.40'),
    ('CMake', '3.27.6'),  # required for awscrt
]

dependencies = [
    ('Python', '3.11.5'),
    ('PyYAML', '6.0.1'),
    ('ruamel.yaml', '0.18.6'),
]

use_pip = True

exts_list = [
    ('jmespath', '1.0.1', {
        'source_tmpl': SOURCE_PY3_WHL,
        'checksums': ['02e2e4cc71b5bcab88332eebf907519190dd9e6e82107fa7f83b1003a6252980'],
    }),
    ('botocore', '1.35.20', {
        'source_tmpl': SOURCE_PY3_WHL,
        'checksums': ['62412038f960691a299e60492f9ee7e8e75af563f2eca7f3640b3b54b8f5d236'],
    }),
    ('s3transfer', '0.10.2', {
        'source_tmpl': SOURCE_PY3_WHL,
        'checksums': ['eca1c20de70a39daee580aef4986996620f365c4e0fda6a86100231d62f1bf69'],
    }),
    ('prompt_toolkit', '3.0.38', {
        'source_tmpl': SOURCE_PY3_WHL,
        'checksums': ['45ea77a2f7c60418850331366c81cf6b5b9cf4c7fd34616f733c5427e6abbb1f'],
    }),
    ('distro', '1.8.0', {
        'source_tmpl': SOURCE_PY3_WHL,
        'checksums': ['99522ca3e365cac527b44bde033f64c6945d90eb9f769703caaec52b09bbd3ff'],
    }),
    ('awscrt', '0.21.2', {
        'preinstallopts': "export AWS_CRT_BUILD_USE_SYSTEM_LIBCRYPTO=1 && ",
        'checksums': ['37ace28d0d7a91f90862dd2994872a15962b7b4f1376e0b7b01a821954611507'],
    }),
    # older version of `urllib3` to avoid `ImportError: cannot import name 'DEFAULT_CIPHERS' from 'urllib3.util.ssl_'`
    # see https://github.com/aws/aws-cli/issues/7905#issuecomment-1559817550
    ('urllib3', '1.26.20', {
        'source_tmpl': SOURCE_WHL,
        'checksums': ['0ed14ccfbf1c30a9072c7ca157e4319b70d65f623e91e7b32fadb2853431016e'],
    }),
    ('cryptography', '40.0.1', {
        'checksums': ['2803f2f8b1e95f614419926c7e6f55d828afc614ca5ed61543877ae668cc3472'],
    }),
    ('docutils', '0.19', {
        'source_tmpl': SOURCE_PY3_WHL,
        'checksums': ['5e1de4d849fee02c63b040a4a3fd567f4ab104defd8a5511fbbc24a8a017efbc'],
    }),
    ('ruamel.yaml', '0.17.21', {
        'source_tmpl': SOURCE_PY3_WHL,
        'checksums': ['742b35d3d665023981bd6d16b3d24248ce5df75fdb4e2924e93a05c1f8b61ca7'],
    }),
    (name, version, {
        'source_tmpl': '%(version)s.tar.gz',
        'source_urls': ['https://github.com/aws/aws-cli/archive/'],
        'checksums': ['ad6f0aa49e103bc4d47590957ed7e05840c2c94f80b4a4c6858d44016a76b3c9'],
    }),
]

sanity_pip_check = True

sanity_check_paths = {
    'files': ['bin/aws'],
    'dirs': ['lib/python%(pyshortver)s/site-packages/'],
}

sanity_check_commands = ["aws help"]

moduleclass = 'tools'

# TODO
# == 2024-09-17 15:12:51,999 build_log.py:171 ERROR EasyBuild crashed with an error (at easybuild/easybuild-framework/easybuild/base/exceptions.py:126 in __init__): cmd "CFLAGS="$CFLAGS -pthread" /apps/gent/RHEL8/cascadelake-ib/software/P
# ython/3.11.5-GCCcore-13.2.0/bin/python -m pip install --prefix=/scratch/gent/vo/001/gvo00117/easybuild/RHEL8/cascadelake-ampere-ib/software/awscli/2.17.52-GCCcore-13.2.0  --no-deps  --ignore-installed  --no-index  --no-build-isolation
# ." exited with exit code 1 and output:
# Processing /tmp/vsc45304/easybuild/build/awscli/2.17.52/GCCcore-13.2.0/cryptography/cryptography-40.0.1
#   Preparing metadata (pyproject.toml): started
#   Preparing metadata (pyproject.toml): finished with status 'error'
#   error: subprocess-exited-with-error
#
#    Preparing metadata (pyproject.toml) did not run successfully.
#    exit code: 1
#   > [24 lines of output]
#
#               =============================DEBUG ASSISTANCE==========================
#               If you are seeing an error here please try the following to
#               successfully install cryptography:
#
#               Upgrade to the latest pip and try again. This will fix errors for most
#               users. See: https://pip.pypa.io/en/stable/installing/#upgrading-pip
#               =============================DEBUG ASSISTANCE==========================
#
#       Traceback (most recent call last):
#         File "/apps/gent/RHEL8/cascadelake-ib/software/Python/3.11.5-GCCcore-13.2.0/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
#           main()
#         File "/apps/gent/RHEL8/cascadelake-ib/software/Python/3.11.5-GCCcore-13.2.0/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
#           json_out['return_val'] = hook(**hook_input['kwargs'])
#                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#         File "/apps/gent/RHEL8/cascadelake-ib/software/Python/3.11.5-GCCcore-13.2.0/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 149, in prepare_metadata_for_build_wheel
#           return hook(metadata_directory, config_settings)
#                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#         File "/apps/gent/RHEL8/cascadelake-ib/software/Python/3.11.5-GCCcore-13.2.0/lib/python3.11/site-packages/setuptools/build_meta.py", line 396, in prepare_metadata_for_build_wheel
#           self.run_setup()
#         File "/apps/gent/RHEL8/cascadelake-ib/software/Python/3.11.5-GCCcore-13.2.0/lib/python3.11/site-packages/setuptools/build_meta.py", line 341, in run_setup
#           exec(code, locals())
#         File "<string>", line 18, in <module>
#       ModuleNotFoundError: No module named 'setuptools_rust'
#       [end of output]
#
#   note: This error originates from a subprocess, and is likely not a problem with pip.
# error: metadata-generation-failed
#
#  Encountered error while generating package metadata.
# > See above for output.
#
# note: This is an issue with the package mentioned above, not pip.
# hint: See above for details.
#  (at easybuild/easybuild-framework/easybuild/tools/run.py:682 in parse_cmd_output)
